/* GENERATED by tools/export-content.mjs from the contents of public/audio/.
 *
 * Empty means there are no recordings yet. That is the current, honest state
 * of the course: see ARCHITECTURE.md §6.3. Everything downstream — the audio
 * button, the listening exercises, the quiz composition — reads this array and
 * degrades visibly rather than inventing a pronunciation. */
export const AUDIO_MANIFEST: readonly string[] = [];
